### ISSUE TITLE
package build

### ISSUE THREAD

**Issue by jburkhardt** [rstats-lab/RGoogleAds#14]
Do we need to add

- RGoogleAds.Rproj
- .google.auth.RData

to .Rbuildignore?

**Comment by mbannert** [comment]
NEED is a strong word :) Really depends on your build chain / build tools. But I don't see how it would hurt. 

And while you're on it you could add this gitignore to the repo, too + add our special things (auth objects etc) if necessary:

https://github.com/github/gitignore/blob/master/R.gitignore
