### ISSUE TITLE
authenticate seems to add lines to gitignore every time around

### ISSUE THREAD

**Issue by mbannert** [rstats-lab/RGoogleAds#5]
see authenticate.R if clause.

**Comment by jburkhardt** [comment]
@mbannert you are right!
after multiple `authenticate()`the `.gitignore` looks like:
```
.Rproj.user
.Rhistory
.RData
.Ruserdata
.google.auth.RData.google.auth.RData
```

**Comment by jburkhardt** [comment]
@mbannert Please check my solution: https://github.com/rstats-lab/RGoogleAds/commit/d345e5b4b64416c8445f1788130897dc9d4e0cd7#diff-7ca13c788d404c1c77c5640d7b29e522R30
What do you think?

**Comment by jburkhardt** [comment]
@mbannert here is an update without `suppressWarnings` https://github.com/rstats-lab/RGoogleAds/commit/d345e5b4b64416c8445f1788130897dc9d4e0cd7
I am happy about further suggestions and improvements!
